# Generated by Django 5.1.5 on 2025-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], max_length=20)),
                ('scalp_type', models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('normal', 'Normal'), ('combination', 'Combination')], max_length=20)),
                ('concerns', models.JSONField(default=list)),
                ('porosity', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
