# Generated by Django 5.1.5 on 2025-12-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairdresser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('services', models.TextField()),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairdresser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hairdresser')),
            ],
        ),
    ]
